from __future__ import annotations

from typing import Any

BUNDLED_MOVIE_GENRES = [
    {"id": 28, "name": "Action", "name_zh": "动作"},
    {"id": 12, "name": "Adventure", "name_zh": "冒险"},
    {"id": 16, "name": "Animation", "name_zh": "动画"},
    {"id": 35, "name": "Comedy", "name_zh": "喜剧"},
    {"id": 80, "name": "Crime", "name_zh": "犯罪"},
    {"id": 99, "name": "Documentary", "name_zh": "纪录"},
    {"id": 18, "name": "Drama", "name_zh": "剧情"},
    {"id": 10751, "name": "Family", "name_zh": "家庭"},
    {"id": 14, "name": "Fantasy", "name_zh": "奇幻"},
    {"id": 36, "name": "History", "name_zh": "历史"},
    {"id": 27, "name": "Horror", "name_zh": "恐怖"},
    {"id": 10402, "name": "Music", "name_zh": "音乐"},
    {"id": 9648, "name": "Mystery", "name_zh": "悬疑"},
    {"id": 10749, "name": "Romance", "name_zh": "爱情"},
    {"id": 878, "name": "Science Fiction", "name_zh": "科幻"},
    {"id": 10770, "name": "TV Movie", "name_zh": "电视电影"},
    {"id": 53, "name": "Thriller", "name_zh": "惊悚"},
    {"id": 10752, "name": "War", "name_zh": "战争"},
    {"id": 37, "name": "Western", "name_zh": "西部"},
]

BUNDLED_TV_GENRES = [
    {"id": 10759, "name": "Action & Adventure", "name_zh": "动作冒险"},
    {"id": 16, "name": "Animation", "name_zh": "动画"},
    {"id": 35, "name": "Comedy", "name_zh": "喜剧"},
    {"id": 80, "name": "Crime", "name_zh": "犯罪"},
    {"id": 99, "name": "Documentary", "name_zh": "纪录"},
    {"id": 18, "name": "Drama", "name_zh": "剧情"},
    {"id": 10751, "name": "Family", "name_zh": "家庭"},
    {"id": 10762, "name": "Kids", "name_zh": "儿童"},
    {"id": 9648, "name": "Mystery", "name_zh": "悬疑"},
    {"id": 10763, "name": "News", "name_zh": "新闻"},
    {"id": 10764, "name": "Reality", "name_zh": "真人秀"},
    {"id": 10765, "name": "Sci-Fi & Fantasy", "name_zh": "科幻奇幻"},
    {"id": 10766, "name": "Soap", "name_zh": "肥皂剧"},
    {"id": 10767, "name": "Talk", "name_zh": "脱口秀"},
    {"id": 10768, "name": "War & Politics", "name_zh": "战争政治"},
    {"id": 37, "name": "Western", "name_zh": "西部"},
]

BUNDLED_COUNTRIES = [
    {"iso_3166_1": "AR", "english_name": "Argentina", "native_name": "阿根廷"},
    {"iso_3166_1": "AU", "english_name": "Australia", "native_name": "澳大利亚"},
    {"iso_3166_1": "BE", "english_name": "Belgium", "native_name": "比利时"},
    {"iso_3166_1": "BR", "english_name": "Brazil", "native_name": "巴西"},
    {"iso_3166_1": "CA", "english_name": "Canada", "native_name": "加拿大"},
    {"iso_3166_1": "CH", "english_name": "Switzerland", "native_name": "瑞士"},
    {"iso_3166_1": "CL", "english_name": "Chile", "native_name": "智利"},
    {"iso_3166_1": "CN", "english_name": "China", "native_name": "中国 内地"},
    {"iso_3166_1": "CO", "english_name": "Colombia", "native_name": "哥伦比亚"},
    {"iso_3166_1": "CZ", "english_name": "Czech Republic", "native_name": "捷克"},
    {"iso_3166_1": "DE", "english_name": "Germany", "native_name": "德国"},
    {"iso_3166_1": "DK", "english_name": "Denmark", "native_name": "丹麦"},
    {"iso_3166_1": "EG", "english_name": "Egypt", "native_name": "埃及"},
    {"iso_3166_1": "ES", "english_name": "Spain", "native_name": "西班牙"},
    {"iso_3166_1": "FI", "english_name": "Finland", "native_name": "芬兰"},
    {"iso_3166_1": "FR", "english_name": "France", "native_name": "法国"},
    {"iso_3166_1": "GB", "english_name": "United Kingdom", "native_name": "英国"},
    {"iso_3166_1": "GR", "english_name": "Greece", "native_name": "希腊"},
    {"iso_3166_1": "HK", "english_name": "Hong Kong", "native_name": "香港"},
    {"iso_3166_1": "ID", "english_name": "Indonesia", "native_name": "印度尼西亚"},
    {"iso_3166_1": "IL", "english_name": "Israel", "native_name": "以色列"},
    {"iso_3166_1": "IN", "english_name": "India", "native_name": "印度"},
    {"iso_3166_1": "IQ", "english_name": "Iraq", "native_name": "伊拉克"},
    {"iso_3166_1": "IR", "english_name": "Iran", "native_name": "伊朗"},
    {"iso_3166_1": "IT", "english_name": "Italy", "native_name": "意大利"},
    {"iso_3166_1": "JP", "english_name": "Japan", "native_name": "日本"},
    {"iso_3166_1": "KP", "english_name": "North Korea", "native_name": "朝鲜"},
    {"iso_3166_1": "KR", "english_name": "South Korea", "native_name": "韩国"},
    {"iso_3166_1": "LA", "english_name": "Laos", "native_name": "老挝"},
    {"iso_3166_1": "MM", "english_name": "Myanmar", "native_name": "缅甸"},
    {"iso_3166_1": "MN", "english_name": "Mongolia", "native_name": "蒙古"},
    {"iso_3166_1": "MO", "english_name": "Macao", "native_name": "澳门"},
    {"iso_3166_1": "MX", "english_name": "Mexico", "native_name": "墨西哥"},
    {"iso_3166_1": "MY", "english_name": "Malaysia", "native_name": "马来西亚"},
    {"iso_3166_1": "NL", "english_name": "Netherlands", "native_name": "荷兰"},
    {"iso_3166_1": "NO", "english_name": "Norway", "native_name": "挪威"},
    {"iso_3166_1": "NZ", "english_name": "New Zealand", "native_name": "新西兰"},
    {"iso_3166_1": "PH", "english_name": "Philippines", "native_name": "菲律宾"},
    {"iso_3166_1": "PK", "english_name": "Pakistan", "native_name": "巴基斯坦"},
    {"iso_3166_1": "PL", "english_name": "Poland", "native_name": "波兰"},
    {"iso_3166_1": "PT", "english_name": "Portugal", "native_name": "葡萄牙"},
    {"iso_3166_1": "RU", "english_name": "Russia", "native_name": "俄罗斯"},
    {"iso_3166_1": "SA", "english_name": "Saudi Arabia", "native_name": "沙特阿拉伯"},
    {"iso_3166_1": "SE", "english_name": "Sweden", "native_name": "瑞典"},
    {"iso_3166_1": "SG", "english_name": "Singapore", "native_name": "新加坡"},
    {"iso_3166_1": "TH", "english_name": "Thailand", "native_name": "泰国"},
    {"iso_3166_1": "TR", "english_name": "Turkey", "native_name": "土耳其"},
    {"iso_3166_1": "TW", "english_name": "Taiwan", "native_name": "中国台湾"},
    {"iso_3166_1": "US", "english_name": "United States of America", "native_name": "美国"},
    {"iso_3166_1": "VN", "english_name": "Vietnam", "native_name": "越南"},
]


def bundled_rule_references() -> dict[str, Any]:
    return {
        "movie_genres": list(BUNDLED_MOVIE_GENRES),
        "tv_genres": list(BUNDLED_TV_GENRES),
        "countries": list(BUNDLED_COUNTRIES),
        "source": "bundled",
    }
